### ISSUE TITLE
Intergrate the SVM `Account Increase Balance`

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/go-svm#14]
After the FFI layer of SVM will expose the `Increase Account Balance` functionality, it should be integrated to `go-svm`
(see SVM Issue: https://github.com/spacemeshos/svm/issues/377)

Right now, `go-svm` has a place-holder for that feature:
https://github.com/spacemeshos/go-svm/blob/710604ce6fcca1f31d3f79a60a8880db98d1ef6d/svm/api.go#L274-L276

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/go-svm/pull/29.
