### ISSUE TITLE
Integrate the SVM `Get Account` 

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/go-svm#15]
The SVM FFI layer exposes the `svm_get_accunt`:
https://github.com/spacemeshos/svm/blob/478d12fddfa87e6230a64010bfd3c0f24ad3164f/crates/runtime-ffi/src/api.rs#L437

We want to `go-svm` to integrate with that API so that `go-spacemesh` could use it.

Right now, there is a place-holder for `GetAccount`:
https://github.com/spacemeshos/go-svm/blob/710604ce6fcca1f31d3f79a60a8880db98d1ef6d/svm/api.go#L260

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/go-svm/pull/29.
