### ISSUE TITLE
Integrate the SVM functionaility required for self-healing

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/go-svm#16]
The SVM FFI layer exposes `svm_rewind`.

link:
https://github.com/spacemeshos/svm/blob/478d12fddfa87e6230a64010bfd3c0f24ad3164f/crates/runtime-ffi/src/api.rs#L417

We need `go-svm` to expose that functionality to be used by `go-spacemesh` as well.
When `go-spacemesh` undergoes a self-healing process, it will ask `go-svm` and for a rewind.

Right now, there is a place-holder implementation:
https://github.com/spacemeshos/go-svm/blob/710604ce6fcca1f31d3f79a60a8880db98d1ef6d/svm/api.go#L244

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/go-svm/pull/29.
