### ISSUE TITLE
Integrate the `Open` API

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/go-svm#18]
This issue is dependant on this issue under the SVM repository:
https://github.com/spacemeshos/svm/issues/402

This issue should add the `go-svm` implementation. Right now, there is a place-holder on the code-base:
https://github.com/spacemeshos/go-svm/blob/710604ce6fcca1f31d3f79a60a8880db98d1ef6d/svm/api.go#L237

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/go-svm/pull/29.
