### ISSUE TITLE
Testing `Spawning` an Account when calling an existing function which is not a `ctor`

### ISSUE THREAD

**Issue by YaronWittenstein** [spacemeshos/go-svm#23]
In continuation of issues #20 and #21 it would be essential to test the following:

* Attempting to spawn an account when the `ctor_name` given is of an existing export function but not a `ctor` one (i.e not part of the `CtorsSection`).

* Calling an existing account when the `func_name` given if of an existing `ctor`

Both tests should of course return an error.

**Comment by neysofu** [comment]
Closed by https://github.com/spacemeshos/go-svm/pull/30/.
